services:
  app:
    build: .
    ports:
      - "8084:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_BASE_URL: ""
      DB_DRIVER: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: beflow_local
      DB_USER: admin
      DB_PASS: admin
      DB_USE_DATABASE_URL: "false"
      DATABASE_URL: postgres://admin:admin@db:5432/beflow_local?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: beflow_local
    volumes:
      - beflow_pgdata:/var/lib/postgresql/data

volumes:
  beflow_pgdata:
